name: Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

# カバレッジの可視化で、コメントを残すための権限
permissions:
  contents: write
  pull-requests: write

jobs:
  cargo:
    runs-on: ubuntu-latest
    env:
      COV_PATH: ./coverage.xml
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 #v4
        with:
          version: 2026.5.15
          cache: true

      - name: run llvm-cov
        run: |
          cargo llvm-cov test --cobertura --output-path ${{ env.COV_PATH }}

      - name: post coverage to comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb
        with:
          minimum_coverage: 75 # カバレッジが75%未満の場合、コメントに警告を残す
