name: Test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  cargo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: run test
        run: |
          cargo test
